name: remind_caldav_client
description: A CalDAV client for re_mind. It allows to make CalDAV
  requests to a server easily and quickly.
version: 1.1.1
repository: https://github.com/BettaSystems/remind_caldav_client
issue_tracker: https://github.com/BettaSystems/remind_caldav_client/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.1
  icalendar_parser: ^2.0.0
  xml: ^6.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.8
  mock_web_server: ^5.0.0-nullsafety.1
